name: Update GitHub Stats in README

on:
  schedule:
    - cron: "0 */2 * * *" # every 2 hours
  workflow_dispatch: # allows manual trigger

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Auto-update README content
        run: |
          echo "🛠️  You can add a script here to update README dynamically"
          # Example: Regenerate stats, insert dynamic data, etc.

      - name: Commit and push if changes exist
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md || exit 0
          git diff --cached --quiet || git commit -m "♻️ auto-update README" && git push
